export const INCREMENT_TICK = 'INCREMENT_TICK';
export const STORE_BEER = 'STORE_BEER';
export const SELL_BEER = 'SELL_BEER';
// export const ADD_INVENTORY_ITEM = 'ADD_INVENTORY_ITEM';
export const OPEN_MARKETPLACE_MODAL = 'OPEN_MARKETPLACE_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const BUY_MARKETPLACE_ITEM = 'BUY_MARKETPLACE_ITEM';
